// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: movie/movie/reviews_allocation.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ReviewsAllocation struct {
	MovieId   uint64   `protobuf:"varint,1,opt,name=movieId,proto3" json:"movieId,omitempty"`
	ReviewIds []uint64 `protobuf:"varint,2,rep,packed,name=reviewIds,proto3" json:"reviewIds,omitempty"`
}

func (m *ReviewsAllocation) Reset()         { *m = ReviewsAllocation{} }
func (m *ReviewsAllocation) String() string { return proto.CompactTextString(m) }
func (*ReviewsAllocation) ProtoMessage()    {}
func (*ReviewsAllocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_6434cbec580ebc96, []int{0}
}
func (m *ReviewsAllocation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReviewsAllocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReviewsAllocation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReviewsAllocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReviewsAllocation.Merge(m, src)
}
func (m *ReviewsAllocation) XXX_Size() int {
	return m.Size()
}
func (m *ReviewsAllocation) XXX_DiscardUnknown() {
	xxx_messageInfo_ReviewsAllocation.DiscardUnknown(m)
}

var xxx_messageInfo_ReviewsAllocation proto.InternalMessageInfo

func (m *ReviewsAllocation) GetMovieId() uint64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

func (m *ReviewsAllocation) GetReviewIds() []uint64 {
	if m != nil {
		return m.ReviewIds
	}
	return nil
}

func init() {
	proto.RegisterType((*ReviewsAllocation)(nil), "movie.movie.ReviewsAllocation")
}

func init() {
	proto.RegisterFile("movie/movie/reviews_allocation.proto", fileDescriptor_6434cbec580ebc96)
}

var fileDescriptor_6434cbec580ebc96 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xc9, 0xcd, 0x2f, 0xcb,
	0x4c, 0xd5, 0x87, 0x90, 0x45, 0xa9, 0x65, 0x99, 0xa9, 0xe5, 0xc5, 0xf1, 0x89, 0x39, 0x39, 0xf9,
	0xc9, 0x89, 0x25, 0x99, 0xf9, 0x79, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xdc, 0x60, 0x79,
	0x3d, 0x30, 0xa9, 0xe4, 0xcd, 0x25, 0x18, 0x04, 0x51, 0xe8, 0x08, 0x57, 0x27, 0x24, 0xc1, 0xc5,
	0x0e, 0x96, 0xf5, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0x82, 0x71, 0x85, 0x64, 0xb8,
	0x38, 0x21, 0xe6, 0x7a, 0xa6, 0x14, 0x4b, 0x30, 0x29, 0x30, 0x6b, 0xb0, 0x04, 0x21, 0x04, 0x9c,
	0x74, 0x4f, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f,
	0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21, 0x4a, 0x18, 0xe2, 0xa6, 0x0a,
	0xa8, 0xdb, 0x4a, 0x2a, 0x0b, 0x52, 0x8b, 0x93, 0xd8, 0xc0, 0xee, 0x31, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x10, 0x7f, 0xd9, 0x4d, 0xb7, 0x00, 0x00, 0x00,
}

func (m *ReviewsAllocation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReviewsAllocation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReviewsAllocation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ReviewIds) > 0 {
		dAtA2 := make([]byte, len(m.ReviewIds)*10)
		var j1 int
		for _, num := range m.ReviewIds {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintReviewsAllocation(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x12
	}
	if m.MovieId != 0 {
		i = encodeVarintReviewsAllocation(dAtA, i, uint64(m.MovieId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintReviewsAllocation(dAtA []byte, offset int, v uint64) int {
	offset -= sovReviewsAllocation(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ReviewsAllocation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MovieId != 0 {
		n += 1 + sovReviewsAllocation(uint64(m.MovieId))
	}
	if len(m.ReviewIds) > 0 {
		l = 0
		for _, e := range m.ReviewIds {
			l += sovReviewsAllocation(uint64(e))
		}
		n += 1 + sovReviewsAllocation(uint64(l)) + l
	}
	return n
}

func sovReviewsAllocation(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozReviewsAllocation(x uint64) (n int) {
	return sovReviewsAllocation(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ReviewsAllocation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReviewsAllocation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReviewsAllocation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReviewsAllocation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MovieId", wireType)
			}
			m.MovieId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReviewsAllocation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MovieId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowReviewsAllocation
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ReviewIds = append(m.ReviewIds, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowReviewsAllocation
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthReviewsAllocation
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthReviewsAllocation
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.ReviewIds) == 0 {
					m.ReviewIds = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowReviewsAllocation
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ReviewIds = append(m.ReviewIds, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ReviewIds", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipReviewsAllocation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReviewsAllocation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipReviewsAllocation(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowReviewsAllocation
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReviewsAllocation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReviewsAllocation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthReviewsAllocation
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupReviewsAllocation
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthReviewsAllocation
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthReviewsAllocation        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowReviewsAllocation          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupReviewsAllocation = fmt.Errorf("proto: unexpected end of group")
)
